steps:

- id: 'tf destroy'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 

    terraform init
    terraform destroy -auto-approve

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd build-terraform
    terraform init
    terraform apply -auto-approve